language: python

python:
  - "2.7"

env:
 - VERSION="7.0" ODOO_REPO="odoo/odoo" EXCLUDE="account_invoice_uos"
 - VERSION="7.0" ODOO_REPO="odoo/odoo" INCLUDE="account_invoice_uos"
 - VERSION="7.0" ODOO_REPO="OCA/OCB" EXCLUDE="account_invoice_uos"
 - VERSION="7.0" ODOO_REPO="OCA/OCB" INCLUDE="account_invoice_uos"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/account-financial-tools.git -b ${VERSION} ${HOME}/account-financial-tools
  - git clone https://github.com/OCA/stock-logistics-workflow.git -b ${VERSION} ${HOME}/stock-logistics-workflow
  - git clone https://github.com/OCA/product-attribute.git -b ${VERSION} ${HOME}/product-attribute
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_flake8
  - travis_run_tests

after_success:
  coveralls
